// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/log.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentLogEntry represents a single log line from agent.
type AgentLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`          // "info", "warn", "error", "debug"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`      // Log content (up to 4096 bytes)
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`        // Log source: "agent" | "core"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentLogEntry) Reset() {
	*x = AgentLogEntry{}
	mi := &file_agent_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentLogEntry) ProtoMessage() {}

func (x *AgentLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentLogEntry.ProtoReflect.Descriptor instead.
func (*AgentLogEntry) Descriptor() ([]byte, []int) {
	return file_agent_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *AgentLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AgentLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentLogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// ReportAgentLogsRequest carries a batch of agent logs.
type ReportAgentLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AgentLogEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`                          // Log entries (max 100 per batch)
	ReportedAt    int64                  `protobuf:"varint,2,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"` // Unix timestamp of upload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAgentLogsRequest) Reset() {
	*x = ReportAgentLogsRequest{}
	mi := &file_agent_v1_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAgentLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAgentLogsRequest) ProtoMessage() {}

func (x *ReportAgentLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAgentLogsRequest.ProtoReflect.Descriptor instead.
func (*ReportAgentLogsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_log_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAgentLogsRequest) GetEntries() []*AgentLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReportAgentLogsRequest) GetReportedAt() int64 {
	if x != nil {
		return x.ReportedAt
	}
	return 0
}

// ReportAgentLogsResponse acknowledges receipt.
type ReportAgentLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Accepted      int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // Number of entries accepted
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAgentLogsResponse) Reset() {
	*x = ReportAgentLogsResponse{}
	mi := &file_agent_v1_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAgentLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAgentLogsResponse) ProtoMessage() {}

func (x *ReportAgentLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAgentLogsResponse.ProtoReflect.Descriptor instead.
func (*ReportAgentLogsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_log_proto_rawDescGZIP(), []int{2}
}

func (x *ReportAgentLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportAgentLogsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *ReportAgentLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_v1_log_proto protoreflect.FileDescriptor

const file_agent_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x12agent/v1/log.proto\x12\bagent.v1\"u\n" +
	"\rAgentLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"l\n" +
	"\x16ReportAgentLogsRequest\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.agent.v1.AgentLogEntryR\aentries\x12\x1f\n" +
	"\vreported_at\x18\x02 \x01(\x03R\n" +
	"reportedAt\"i\n" +
	"\x17ReportAgentLogsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB:Z8github.com/creamcroissant/mgpanel/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_log_proto_rawDescOnce sync.Once
	file_agent_v1_log_proto_rawDescData []byte
)

func file_agent_v1_log_proto_rawDescGZIP() []byte {
	file_agent_v1_log_proto_rawDescOnce.Do(func() {
		file_agent_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_log_proto_rawDesc), len(file_agent_v1_log_proto_rawDesc)))
	})
	return file_agent_v1_log_proto_rawDescData
}

var file_agent_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agent_v1_log_proto_goTypes = []any{
	(*AgentLogEntry)(nil),           // 0: agent.v1.AgentLogEntry
	(*ReportAgentLogsRequest)(nil),  // 1: agent.v1.ReportAgentLogsRequest
	(*ReportAgentLogsResponse)(nil), // 2: agent.v1.ReportAgentLogsResponse
}
var file_agent_v1_log_proto_depIdxs = []int32{
	0, // 0: agent.v1.ReportAgentLogsRequest.entries:type_name -> agent.v1.AgentLogEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_v1_log_proto_init() }
func file_agent_v1_log_proto_init() {
	if File_agent_v1_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_log_proto_rawDesc), len(file_agent_v1_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_log_proto_goTypes,
		DependencyIndexes: file_agent_v1_log_proto_depIdxs,
		MessageInfos:      file_agent_v1_log_proto_msgTypes,
	}.Build()
	File_agent_v1_log_proto = out.File
	file_agent_v1_log_proto_goTypes = nil
	file_agent_v1_log_proto_depIdxs = nil
}
