// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/mesh.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JoinMeshRequest is sent by Agent to join the WireGuard mesh network.
type JoinMeshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"` // Network ID (default: "default")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMeshRequest) Reset() {
	*x = JoinMeshRequest{}
	mi := &file_agent_v1_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMeshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeshRequest) ProtoMessage() {}

func (x *JoinMeshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeshRequest.ProtoReflect.Descriptor instead.
func (*JoinMeshRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *JoinMeshRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

// JoinMeshResponse is returned by Panel after mesh join.
type JoinMeshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WgPrivateKey  string                 `protobuf:"bytes,2,opt,name=wg_private_key,json=wgPrivateKey,proto3" json:"wg_private_key,omitempty"`
	WgPublicKey   string                 `protobuf:"bytes,3,opt,name=wg_public_key,json=wgPublicKey,proto3" json:"wg_public_key,omitempty"`
	WgIp          string                 `protobuf:"bytes,4,opt,name=wg_ip,json=wgIp,proto3" json:"wg_ip,omitempty"`
	WgListenPort  int32                  `protobuf:"varint,5,opt,name=wg_listen_port,json=wgListenPort,proto3" json:"wg_listen_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMeshResponse) Reset() {
	*x = JoinMeshResponse{}
	mi := &file_agent_v1_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMeshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeshResponse) ProtoMessage() {}

func (x *JoinMeshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeshResponse.ProtoReflect.Descriptor instead.
func (*JoinMeshResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *JoinMeshResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinMeshResponse) GetWgPrivateKey() string {
	if x != nil {
		return x.WgPrivateKey
	}
	return ""
}

func (x *JoinMeshResponse) GetWgPublicKey() string {
	if x != nil {
		return x.WgPublicKey
	}
	return ""
}

func (x *JoinMeshResponse) GetWgIp() string {
	if x != nil {
		return x.WgIp
	}
	return ""
}

func (x *JoinMeshResponse) GetWgListenPort() int32 {
	if x != nil {
		return x.WgListenPort
	}
	return 0
}

// GetMeshPeersRequest asks for the list of all mesh peers.
type GetMeshPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeshPeersRequest) Reset() {
	*x = GetMeshPeersRequest{}
	mi := &file_agent_v1_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeshPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeshPeersRequest) ProtoMessage() {}

func (x *GetMeshPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeshPeersRequest.ProtoReflect.Descriptor instead.
func (*GetMeshPeersRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *GetMeshPeersRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

// MeshPeerEntry describes a single WireGuard mesh peer.
type MeshPeerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Keepalive     int32                  `protobuf:"varint,5,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshPeerEntry) Reset() {
	*x = MeshPeerEntry{}
	mi := &file_agent_v1_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPeerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPeerEntry) ProtoMessage() {}

func (x *MeshPeerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPeerEntry.ProtoReflect.Descriptor instead.
func (*MeshPeerEntry) Descriptor() ([]byte, []int) {
	return file_agent_v1_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *MeshPeerEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeshPeerEntry) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *MeshPeerEntry) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MeshPeerEntry) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *MeshPeerEntry) GetKeepalive() int32 {
	if x != nil {
		return x.Keepalive
	}
	return 0
}

// GetMeshPeersResponse returns the list of mesh peers.
type GetMeshPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Peers         []*MeshPeerEntry       `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeshPeersResponse) Reset() {
	*x = GetMeshPeersResponse{}
	mi := &file_agent_v1_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeshPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeshPeersResponse) ProtoMessage() {}

func (x *GetMeshPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeshPeersResponse.ProtoReflect.Descriptor instead.
func (*GetMeshPeersResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *GetMeshPeersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMeshPeersResponse) GetPeers() []*MeshPeerEntry {
	if x != nil {
		return x.Peers
	}
	return nil
}

// RouteEntry is a single priority routing rule for mesh traffic.
type RouteEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`                  // 1=highest
	PeerWgIp      string                 `protobuf:"bytes,3,opt,name=peer_wg_ip,json=peerWgIp,proto3" json:"peer_wg_ip,omitempty"` // 10.144.0.x
	PeerPort      int32                  `protobuf:"varint,4,opt,name=peer_port,json=peerPort,proto3" json:"peer_port,omitempty"`  // 51820
	LatencyMs     float64                `protobuf:"fixed64,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	PacketLoss    float64                `protobuf:"fixed64,6,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_agent_v1_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_agent_v1_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *RouteEntry) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RouteEntry) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RouteEntry) GetPeerWgIp() string {
	if x != nil {
		return x.PeerWgIp
	}
	return ""
}

func (x *RouteEntry) GetPeerPort() int32 {
	if x != nil {
		return x.PeerPort
	}
	return 0
}

func (x *RouteEntry) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RouteEntry) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

// SetRoutingTablesPayload is the payload carried by agent command set_routing_table.
type SetRoutingTablesPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteEntry          `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoutingTablesPayload) Reset() {
	*x = SetRoutingTablesPayload{}
	mi := &file_agent_v1_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoutingTablesPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoutingTablesPayload) ProtoMessage() {}

func (x *SetRoutingTablesPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoutingTablesPayload.ProtoReflect.Descriptor instead.
func (*SetRoutingTablesPayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *SetRoutingTablesPayload) GetRoutes() []*RouteEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_agent_v1_mesh_proto protoreflect.FileDescriptor

const file_agent_v1_mesh_proto_rawDesc = "" +
	"\n" +
	"\x13agent/v1/mesh.proto\x12\bagent.v1\"0\n" +
	"\x0fJoinMeshRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\"\xb1\x01\n" +
	"\x10JoinMeshResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x0ewg_private_key\x18\x02 \x01(\tR\fwgPrivateKey\x12\"\n" +
	"\rwg_public_key\x18\x03 \x01(\tR\vwgPublicKey\x12\x13\n" +
	"\x05wg_ip\x18\x04 \x01(\tR\x04wgIp\x12$\n" +
	"\x0ewg_listen_port\x18\x05 \x01(\x05R\fwgListenPort\"4\n" +
	"\x13GetMeshPeersRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\"\x99\x01\n" +
	"\rMeshPeerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x12\x1c\n" +
	"\tkeepalive\x18\x05 \x01(\x05R\tkeepalive\"_\n" +
	"\x14GetMeshPeersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x05peers\x18\x02 \x03(\v2\x17.agent.v1.MeshPeerEntryR\x05peers\"\xbc\x01\n" +
	"\n" +
	"RouteEntry\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x1c\n" +
	"\n" +
	"peer_wg_ip\x18\x03 \x01(\tR\bpeerWgIp\x12\x1b\n" +
	"\tpeer_port\x18\x04 \x01(\x05R\bpeerPort\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x01R\tlatencyMs\x12\x1f\n" +
	"\vpacket_loss\x18\x06 \x01(\x01R\n" +
	"packetLoss\"G\n" +
	"\x17SetRoutingTablesPayload\x12,\n" +
	"\x06routes\x18\x01 \x03(\v2\x14.agent.v1.RouteEntryR\x06routesB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_mesh_proto_rawDescOnce sync.Once
	file_agent_v1_mesh_proto_rawDescData []byte
)

func file_agent_v1_mesh_proto_rawDescGZIP() []byte {
	file_agent_v1_mesh_proto_rawDescOnce.Do(func() {
		file_agent_v1_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_mesh_proto_rawDesc), len(file_agent_v1_mesh_proto_rawDesc)))
	})
	return file_agent_v1_mesh_proto_rawDescData
}

var file_agent_v1_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_v1_mesh_proto_goTypes = []any{
	(*JoinMeshRequest)(nil),         // 0: agent.v1.JoinMeshRequest
	(*JoinMeshResponse)(nil),        // 1: agent.v1.JoinMeshResponse
	(*GetMeshPeersRequest)(nil),     // 2: agent.v1.GetMeshPeersRequest
	(*MeshPeerEntry)(nil),           // 3: agent.v1.MeshPeerEntry
	(*GetMeshPeersResponse)(nil),    // 4: agent.v1.GetMeshPeersResponse
	(*RouteEntry)(nil),              // 5: agent.v1.RouteEntry
	(*SetRoutingTablesPayload)(nil), // 6: agent.v1.SetRoutingTablesPayload
}
var file_agent_v1_mesh_proto_depIdxs = []int32{
	3, // 0: agent.v1.GetMeshPeersResponse.peers:type_name -> agent.v1.MeshPeerEntry
	5, // 1: agent.v1.SetRoutingTablesPayload.routes:type_name -> agent.v1.RouteEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_v1_mesh_proto_init() }
func file_agent_v1_mesh_proto_init() {
	if File_agent_v1_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_mesh_proto_rawDesc), len(file_agent_v1_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_mesh_proto_goTypes,
		DependencyIndexes: file_agent_v1_mesh_proto_depIdxs,
		MessageInfos:      file_agent_v1_mesh_proto_msgTypes,
	}.Build()
	File_agent_v1_mesh_proto = out.File
	file_agent_v1_mesh_proto_goTypes = nil
	file_agent_v1_mesh_proto_depIdxs = nil
}
