// Code generated by tools/gentypes. DO NOT EDIT.
// Source: internal/service/config_center_spec_validation.go,internal/template/unified.go,internal/template/types.go

export interface UnifiedBrutal {
  enabled: boolean | undefined;
  up_mbps?: number;
  down_mbps?: number;
}

export interface UnifiedInbound {
  tag: string;
  protocol: string;  // vless, vmess, shadowsocks, trojan
  listen: string;
  port: number;
  transport?: UnifiedTransport | null;
  tls?: UnifiedTLS | null;
  users?: UnifiedUser[];
  options?: Record<string, unknown>;
  multiplex?: UnifiedMultiplex | null;
  sniffing?: UnifiedSniffing | null;
}

export interface UnifiedMultiplex {
  enabled: boolean | undefined;
  protocol?: string;
  max_streams?: number;
  padding?: boolean | undefined;
  brutal?: UnifiedBrutal | null;
}

export interface UnifiedReality {
  enabled: boolean | undefined;
  private_key?: string;
  public_key?: string;
  short_ids?: string[];
  server_names?: string[];  // 支持多 SNI 防探测
  handshake_server?: string;
  handshake_port?: number;
  fingerprint?: string;
}

export interface UnifiedSniffing {
  enabled: boolean | undefined;
  dest_override?: string[];
  metadata_only?: boolean | undefined;
  domains_excluded?: string[];
  route_only?: boolean | undefined;
}

export interface UnifiedTLS {
  enabled: boolean | undefined;
  server_name?: string;
  alpn?: string[];
  cert_path?: string;
  key_path?: string;
  reality?: UnifiedReality | null;
}

export interface UnifiedTransport {
  type: string;  // tcp, ws, grpc, http, h2, quic, xhttp
  path?: string;
  host?: string;
  service_name?: string;
  headers?: Record<string, string>;
  mode?: string;
  xhttp?: XHTTPConfig | null;
}

export interface UnifiedUser {
  uuid?: string;
  email?: string;
  password?: string;
  flow?: string;
  method?: string;
}

export interface XHTTPConfig {
  host?: string;
  path?: string;
  mode?: string;
  headers?: Record<string, string>;
  extra?: Record<string, unknown>;
  xmux?: Record<string, unknown>;
  downloadSettings?: Record<string, unknown>;
  noGRPCHeader?: boolean | undefined | null;
  noSSEHeader?: boolean | undefined | null;
  scMaxBufferedPosts?: number | null;
  scMaxEachPostBytes?: number | null;
  scMinPostsIntervalMs?: number | null;
  scStreamUpServerSecs?: number | null;
}

