// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: app/proxyman/command/command.proto

package proxymancommand

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	xrayprotocol "github.com/creamcroissant/mgpanel/pkg/pb/xray/common/protocol"
	xrayserial "github.com/creamcroissant/mgpanel/pkg/pb/xray/common/serial"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddUserOperation adds a user to an inbound via AlterInbound.
type AddUserOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	User *xrayprotocol.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache protoimpl.SizeCache
}

func (x *AddUserOperation) Reset() {
	*x = AddUserOperation{}
	mi := &file_app_proxyman_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserOperation) ProtoMessage() {}

func (x *AddUserOperation) ProtoReflect() protoreflect.Message {
	mi := &file_app_proxyman_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserOperation.ProtoReflect.Descriptor instead.
func (*AddUserOperation) Descriptor() ([]byte, []int) {
	return file_app_proxyman_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserOperation) GetUser() *xrayprotocol.User {
	if x != nil {
		return x.User
	}
	return nil
}

// RemoveUserOperation removes a user from an inbound via AlterInbound.
type RemoveUserOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache protoimpl.SizeCache
}

func (x *RemoveUserOperation) Reset() {
	*x = RemoveUserOperation{}
	mi := &file_app_proxyman_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserOperation) ProtoMessage() {}

func (x *RemoveUserOperation) ProtoReflect() protoreflect.Message {
	mi := &file_app_proxyman_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserOperation.ProtoReflect.Descriptor instead.
func (*RemoveUserOperation) Descriptor() ([]byte, []int) {
	return file_app_proxyman_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveUserOperation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// AlterInboundRequest alters an inbound by tag with a TypedMessage operation.
type AlterInboundRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Operation *xrayserial.TypedMessage `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache protoimpl.SizeCache
}

func (x *AlterInboundRequest) Reset() {
	*x = AlterInboundRequest{}
	mi := &file_app_proxyman_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterInboundRequest) ProtoMessage() {}

func (x *AlterInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proxyman_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterInboundRequest.ProtoReflect.Descriptor instead.
func (*AlterInboundRequest) Descriptor() ([]byte, []int) {
	return file_app_proxyman_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *AlterInboundRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AlterInboundRequest) GetOperation() *xrayserial.TypedMessage {
	if x != nil {
		return x.Operation
	}
	return nil
}

// AlterInboundResponse is the response to AlterInbound.
type AlterInboundResponse struct {
	unknownFields protoimpl.UnknownFields
	sizeCache protoimpl.SizeCache
}

func (x *AlterInboundResponse) Reset() {
	*x = AlterInboundResponse{}
	mi := &file_app_proxyman_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterInboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterInboundResponse) ProtoMessage() {}

func (x *AlterInboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proxyman_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterInboundResponse.ProtoReflect.Descriptor instead.
func (*AlterInboundResponse) Descriptor() ([]byte, []int) {
	return file_app_proxyman_command_command_proto_rawDescGZIP(), []int{3}
}

// GetInboundUserRequest lists users by (tag, email).
type GetInboundUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache protoimpl.SizeCache
}

func (x *GetInboundUserRequest) Reset() {
	*x = GetInboundUserRequest{}
	mi := &file_app_proxyman_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUserRequest) ProtoMessage() {}

func (x *GetInboundUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proxyman_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUserRequest.ProtoReflect.Descriptor instead.
func (*GetInboundUserRequest) Descriptor() ([]byte, []int) {
	return file_app_proxyman_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetInboundUserRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetInboundUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// GetInboundUserResponse returns a list of inbound users.
type GetInboundUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Users []*xrayprotocol.User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache protoimpl.SizeCache
}

func (x *GetInboundUserResponse) Reset() {
	*x = GetInboundUserResponse{}
	mi := &file_app_proxyman_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUserResponse) ProtoMessage() {}

func (x *GetInboundUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proxyman_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUserResponse.ProtoReflect.Descriptor instead.
func (*GetInboundUserResponse) Descriptor() ([]byte, []int) {
	return file_app_proxyman_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *GetInboundUserResponse) GetUsers() []*xrayprotocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

// GetInboundUsersCountResponse returns the number of inbound users.
type GetInboundUsersCountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache protoimpl.SizeCache
}

func (x *GetInboundUsersCountResponse) Reset() {
	*x = GetInboundUsersCountResponse{}
	mi := &file_app_proxyman_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUsersCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUsersCountResponse) ProtoMessage() {}

func (x *GetInboundUsersCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proxyman_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUsersCountResponse.ProtoReflect.Descriptor instead.
func (*GetInboundUsersCountResponse) Descriptor() ([]byte, []int) {
	return file_app_proxyman_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *GetInboundUsersCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_app_proxyman_command_command_proto protoreflect.FileDescriptor

const file_app_proxyman_command_command_proto_rawDesc = "" +
	"\n\"app/proxyman" +
	"/command/comma" +
	"nd.proto\x12\x19xray" +
	".app.proxyman." +
	"command\x1a\x1acommo" +
	"n/protocol/use" +
	"r.proto\x1a!commo" +
	"n/serial/typed" +
	"_message.proto" +
	"\"B\n\x10AddUserOpe" +
	"ration\x12.\n\x04user" +
	"\x18\x01 \x01(\x0b2\x1a.xray." +
	"common.protoco" +
	"l.UserR\x04user\"+" +
	"\n\x13RemoveUserOp" +
	"eration\x12\x14\n\x05ema" +
	"il\x18\x01 \x01(\tR\x05emai" +
	"l\"g\n\x13AlterInbo" +
	"undRequest\x12\x10\n\x03" +
	"tag\x18\x01 \x01(\tR\x03tag" +
	"\x12>\n\toperation\x18" +
	"\x02 \x01(\x0b2 .xray.c" +
	"ommon.serial.T" +
	"ypedMessageR\to" +
	"peration\"\x16\n\x14Al" +
	"terInboundResp" +
	"onse\"?\n\x15GetInb" +
	"oundUserReques" +
	"t\x12\x10\n\x03tag\x18\x01 \x01(\t" +
	"R\x03tag\x12\x14\n\x05email" +
	"\x18\x02 \x01(\tR\x05email\"" +
	"J\n\x16GetInboundU" +
	"serResponse\x120\n" +
	"\x05users\x18\x01 \x03(\x0b2\x1a" +
	".xray.common.p" +
	"rotocol.UserR\x05" +
	"users\"4\n\x1cGetIn" +
	"boundUsersCoun" +
	"tResponse\x12\x14\n\x05c" +
	"ount\x18\x01 \x01(\x03R\x05co" +
	"unt2\xfd\x02\n\x0eHandle" +
	"rService\x12o\n\x0cAl" +
	"terInbound\x12..x" +
	"ray.app.proxym" +
	"an.command.Alt" +
	"erInboundReque" +
	"st\x1a/.xray.app." +
	"proxyman.comma" +
	"nd.AlterInboun" +
	"dResponse\x12v\n\x0fG" +
	"etInboundUsers" +
	"\x120.xray.app.pr" +
	"oxyman.command" +
	".GetInboundUse" +
	"rRequest\x1a1.xra" +
	"y.app.proxyman" +
	".command.GetIn" +
	"boundUserRespo" +
	"nse\x12\x81\x01\n\x14GetInb" +
	"oundUsersCount" +
	"\x120.xray.app.pr" +
	"oxyman.command" +
	".GetInboundUse" +
	"rRequest\x1a7.xra" +
	"y.app.proxyman" +
	".command.GetIn" +
	"boundUsersCoun" +
	"tResponseBCZAg" +
	"ithub.com/crea" +
	"mcroissant/xbo" +
	"ard/pkg/pb/xra" +
	"y/app/proxyman" +
	"/commandb\x06prot" +
	"o3"

var (
	file_app_proxyman_command_command_proto_rawDescOnce sync.Once
	file_app_proxyman_command_command_proto_rawDescData []byte
)

func file_app_proxyman_command_command_proto_rawDescGZIP() []byte {
	file_app_proxyman_command_command_proto_rawDescOnce.Do(func() {
		file_app_proxyman_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_proxyman_command_command_proto_rawDesc), len(file_app_proxyman_command_command_proto_rawDesc)))
	})
	return file_app_proxyman_command_command_proto_rawDescData
}


var file_app_proxyman_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 7)


var file_app_proxyman_command_command_proto_goTypes = []any{
	(*AddUserOperation)(nil), // 0: proxymancommand.AddUserOperation
	(*RemoveUserOperation)(nil), // 1: proxymancommand.RemoveUserOperation
	(*AlterInboundRequest)(nil), // 2: proxymancommand.AlterInboundRequest
	(*AlterInboundResponse)(nil), // 3: proxymancommand.AlterInboundResponse
	(*GetInboundUserRequest)(nil), // 4: proxymancommand.GetInboundUserRequest
	(*GetInboundUserResponse)(nil), // 5: proxymancommand.GetInboundUserResponse
	(*GetInboundUsersCountResponse)(nil), // 6: proxymancommand.GetInboundUsersCountResponse
	(*xrayprotocol.User)(nil), // 7: xrayprotocol.User
	(*xrayserial.TypedMessage)(nil), // 8: xrayserial.TypedMessage
}
var file_app_proxyman_command_command_proto_depIdxs = []int32{
	7, // 0: proxymancommand.AddUserOperation.User:type_name -> xrayprotocol.User
	8, // 1: proxymancommand.AlterInboundRequest.Operation:type_name -> xrayserial.TypedMessage
	7, // 2: proxymancommand.GetInboundUserResponse.Users:type_name -> xrayprotocol.User
	2, // 3: proxymancommand.HandlerService.AlterInbound:input_type -> proxymancommand.AlterInboundRequest
	4, // 4: proxymancommand.HandlerService.GetInboundUsers:input_type -> proxymancommand.GetInboundUserRequest
	4, // 5: proxymancommand.HandlerService.GetInboundUsersCount:input_type -> proxymancommand.GetInboundUserRequest
	3, // 6: proxymancommand.HandlerService.AlterInbound:output_type -> proxymancommand.AlterInboundResponse
	5, // 7: proxymancommand.HandlerService.GetInboundUsers:output_type -> proxymancommand.GetInboundUserResponse
	6, // 8: proxymancommand.HandlerService.GetInboundUsersCount:output_type -> proxymancommand.GetInboundUsersCountResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}


func init() { file_app_proxyman_command_command_proto_init() }
func file_app_proxyman_command_command_proto_init() {
	if File_app_proxyman_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_proxyman_command_command_proto_rawDesc), len(file_app_proxyman_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_proxyman_command_command_proto_goTypes,
		DependencyIndexes: file_app_proxyman_command_command_proto_depIdxs,
		MessageInfos:      file_app_proxyman_command_command_proto_msgTypes,
	}.Build()
	File_app_proxyman_command_command_proto = out.File
	file_app_proxyman_command_command_proto_goTypes = nil
	file_app_proxyman_command_command_proto_depIdxs = nil
}

